### ISSUE TITLE
or comparison not detecting

### ISSUE THREAD

**Issue by grayghostvisuals** [assemble/gulp-assemble#22]
I've been trying my hardest to get this working but no luck. I get the basename reported correct but the conditional blocks I'm using don't seem to work. I tried using handlebars helpers for assemble but kept getting errors in the shell about a ``)`` that does not make sense because without the handlebars require line it compiles fine. [http://www.codeshare.io/gH8Lu](http://www.codeshare.io/gH8Lu)

**Comment by jonschlinkert** [comment]
hey @grayghostvisuals! you're using gulp-assemble with v0.6.0 assemble I assume? 

Can you give more detail about your setup? Have you tried using assemble directly? Is the `or` helper a built-in helper or a custom one?

**Comment by grayghostvisuals** [comment]
> you're using gulp-assemble with v0.6.0 assemble I assume?

yup

> Can you give more detail about your setup? Have you tried using assemble directly? Is the or helper a built-in helper or a custom one?

Can you tell me exactly what it takes to make what I desire come to fruition? Maybe I can do some checks on my end first before going nuts with a setup discussion? I did however include my package.json contents in that codeshare I linked above. Thanks for your help :) BTW I'm not using any helpers or custom ones as I do not know enough atm on how to do such a thing.

**Comment by doowb** [comment]
@grayghostvisuals is this for the transformicons project? You're not using `gulp-assemble` in that project, just `assemble 0.6.0`.

`assemble 0.6.0` automatically includes helpers from [handlebars-helpers#0.6.0](https://github.com/assemble/handlebars-helpers/tree/v0.6.0). 

The [contains](https://github.com/assemble/handlebars-helpers/blob/v0.6.0/lib/helpers/comparisons.js#L17) helper is probably your best bet for getting what you want, but you can't just pass in a bunch of items to compare, you need to pass in a collection, then a search value:

```hbs
{{#contains items this.basename}}
  <div>In items</div>
{{else}}
  <div>Not in items</div>
{{/contains}}
```

`items` should be a property in the context like the page front matter:

```hbs
---
items: 
  - index
  - docs
---
```
This is a good stackoverflow question since it's really about how to use handlebars helpers in assemble.

**Comment by grayghostvisuals** [comment]
@doowb nope this is a styleguide I'm making for a client. I'm eventually releasing it as an Open Source tool that I will also be sharing for a Tuts+ article.

What I'm trying to do is not have certain script blocks load in single page case studies for the style guide. Each component has it's own individual case study in a sep. ``page.hbs`` template.  I put my example in the codeshare above for you. :)

**Comment by doowb** [comment]
Since this is a new project, I'd recommend using `assemble 0.6.0` directly since it's easier to support and track down issues.

Asking this on the assemble repo or stackoverflow can also get more eyes on it to try to help out.
Also an actual example repo might help since the project structure will be easier to understand than just the codeshare that contains everything in one big file. (I was about to give another answer but just realized that I don't fully understand the problem).
