### ISSUE TITLE
Does not work with *.html files. Is *.hbs extension required?

### ISSUE THREAD

**Issue by LukeAskew** [assemble/gulp-assemble#25]
Does assemble require you use the `.hbs` extension? That's what I'm gathering from [this response](https://github.com/assemble/assemble/issues/675#issuecomment-86990013)

Is there a way to force assemble to respect `.html` files and still use Handlbars as the engine? I am writing templates with Handlebars, but don't like the arbitrary file extension.

**Comment by doowb** [comment]
We removed the "catch-all" engine because it didn't make sense to try to render styles or images with handlebars. If you'd like to setup the default engine (we use `engine-assemble`) to render `.html` then you can do this:

```js
var assemble = require('assemble');

// either include 'engine-assemble' in your package.json
// or require it from assemble's node_modules directly
var engine = require('assemble/node_modules/engine-assemble');
assemble.engine('.html', engine);
```

`engine-assemble` includes the helpers from [handlebars-helpers 0.6.0](https://github.com/assemble/handlebars-helpers/tree/v0.6.0).

**Comment by LukeAskew** [comment]
Works! :ok_hand: :tophat:
