### ISSUE TITLE
Drops files with same basename

### ISSUE THREAD

**Issue by LukeAskew** [assemble/gulp-assemble#31]
I have a file glob that matches:

```
src/accessibility.md
src/contributing.md
src/index.md
src/standards/front-end/html.md
src/standards/front-end/index.md
src/standards/front-end/js.md
src/standards/front-end/sass.md
```

but after running through gulp-assemble, **only the second `index.md` is passed through the pipe**; the first `index.md` @ `src/index.md` is dropped from the stream and never makes it to my output directory.

Here's my gulp setup for clarity:

```javascript
var assemble = require('assemble');
var engine = require('assemble/node_modules/engine-assemble');

module.exports = function(gulp, $, pkg) {

	var htmlFiles = pkg.cfg.files.html,
		opts = pkg.cfg.plugins;

	gulp.task('html', function() {

		assemble.layouts('src/layouts/**/*');
		assemble.partials(['src/partials/**/*']);
		assemble.option('layout', 'default');
		assemble.engine('.html', engine);

		return gulp.src(htmlFiles.src)
			.pipe($.gulpAssemble(assemble))
			.pipe($.extname())
			.pipe($.highlight())
			.pipe(gulp.dest(htmlFiles.dest))
			.pipe($.connect.reload());
	});

};
```

**Comment by jonschlinkert** [comment]
Templates are cached on an object, and by default the basename of the object is used. since objects must have unique keys, only one template is getting cached. 

There is a workaround. You can pass a `renameKey` function on the options:

```js
assemble.option('renameKey', function(fp) {
  return fp;
});
```

Keep in mind that if you change how the key is stored, e.g. like by the full filepath, you'll also need to reference templates that way. You can always implement logic in middleware or helpers to extend the path to what you need it to be as well. 

We're working on some ideas to make this better, but in the meantime, hope this helps...

**Comment by LukeAskew** [comment]
Thanks!
